// AUTO-GENERATED by scripts/select-model.js. Do not edit manually.
import type { WeddingModel } from './model.types';

export const ACTIVE_MODEL: WeddingModel = {
  name: 'modelo-02',
  displayName: 'Modelo 02',
  pageModulePath: './main/pages/modelo-02/modelo-02-page.component',
  exportName: 'Modelo02PageComponent',
  supportsThemes: false,
};
