// AUTO-GENERATED by scripts/select-model.js. Do not edit manually.
import type { WeddingModel } from './model.types';

export const ACTIVE_MODEL: WeddingModel = {
  name: 'model-01',
  displayName: 'Model 01',
  pageModulePath: './features/model-01/pages/wedding-page/wedding-page.component',
  exportName: 'WeddingPageComponent',
  supportsThemes: true,
};
