// AUTO-GENERATED by scripts/select-model.js. Do not edit manually.
import { Routes } from '@angular/router';

export const weddingPageRoute = {
  path: '',
  loadComponent: () =>
    import('./features/model-01/pages/wedding-page/wedding-page.component').then((m) => m.WeddingPageComponent),
};

export const generatedRoutes: Routes = [weddingPageRoute];
