// AUTO-GENERATED by scripts/select-model.js. Do not edit manually.
import { Routes } from '@angular/router';

export const weddingPageRoute = {
  path: '',
  loadComponent: () =>
    import('./main/pages/modelo-02/modelo-02-page.component').then((m) => m.Modelo02PageComponent),
};

export const generatedRoutes: Routes = [weddingPageRoute];
