const { existsSync, mkdirSync, readFileSync, writeFileSync } = require('node:fs');
const path = require('node:path');
const { generateThemeAssets } = require('./generate-theme-assets');

const DEFAULT_THEME = 'hojas-navy';

const THEMES = {
  'hojas-navy': {
    exportName: 'TEMPLATE_HOJAS_NAVY',
    moduleName: './template-hojas-navy.theme',
  },
  'hojas-forest': {
    exportName: 'TEMPLATE_HOJAS_FOREST',
    moduleName: './template-hojas-forest.theme',
  },
};

function readExistingThemeName(rootDir = process.cwd()) {
  const activeThemePath = path.join(rootDir, 'src', 'app', 'themes', 'active-theme.ts');

  if (!existsSync(activeThemePath)) {
    return undefined;
  }

  const contents = readFileSync(activeThemePath, 'utf8');
  const theme = Object.entries(THEMES).find(([, config]) => contents.includes(config.exportName));

  return theme?.[0];
}

function resolveThemeName(explicitTheme, env = process.env, rootDir = process.cwd()) {
  const themeName = explicitTheme || env.TEMPLATE_THEME || readExistingThemeName(rootDir) || DEFAULT_THEME;

  if (!THEMES[themeName]) {
    const availableThemes = Object.keys(THEMES).join(', ');
    throw new Error(`Unknown theme "${themeName}". Available themes: ${availableThemes}`);
  }

  return themeName;
}

function writeActiveThemeFile(themeName, rootDir = process.cwd()) {
  const theme = THEMES[themeName];
  const themesDir = path.join(rootDir, 'src', 'app', 'themes');
  const activeThemePath = path.join(themesDir, 'active-theme.ts');
  const contents = [
    '// AUTO-GENERATED by scripts/select-theme.js. Do not edit manually.',
    `export { ${theme.exportName} as ACTIVE_THEME } from '${theme.moduleName}';`,
    '',
  ].join('\n');

  mkdirSync(themesDir, { recursive: true });
  writeFileSync(activeThemePath, contents);

  return activeThemePath;
}

function main(argv = process.argv.slice(2), env = process.env, rootDir = process.cwd()) {
  const themeName = resolveThemeName(argv[0], env, rootDir);
  const activeThemePath = writeActiveThemeFile(themeName, rootDir);
  generateThemeAssets(themeName, rootDir);

  console.log(`Selected theme: ${themeName}`);
  console.log(`Generated: ${path.relative(rootDir, activeThemePath)}`);
  console.log('Generated: src\\assets\\generated\\active');
}

if (require.main === module) {
  main();
}

module.exports = {
  DEFAULT_THEME,
  THEMES,
  main,
  readExistingThemeName,
  resolveThemeName,
  writeActiveThemeFile,
};
